### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by noahdjroton** [Romulad/figma-to-code-ed2-week1#1]
1 - Prends le soin de bien nommer tes fichiers et assure-toi d'avoir un style de notation uniforme, sans mélanger PascalCase, camelCase et kebab-case.

- Bien nommer les sections au lieu d'utiliser `FirstSection` `SecondSection` `ThirdSection`

<img width="228" alt="Screenshot 2024-08-04 at 20 17 58" src="https://github.com/user-attachments/assets/211a6bda-6db0-42ba-9eec-27417190127e">

Lien utile : https://www.curiouslychase.com/posts/most-common-programming-case-types/

2 - Utilise des alias pour importer les fichiers au lieu d'utiliser des chemins relatifs ou absolus.

<img width="827" alt="Screenshot 2024-08-04 at 20 19 59" src="https://github.com/user-attachments/assets/67b0af4c-c2a8-4708-8404-6c93881826bf">

Lien utile : https://nextjs.org/docs/app/building-your-application/configuring/absolute-imports-and-module-aliases

3 - Prends le soin de bien nommer tes commits. Ta façon actuelle de nommer tes commits ne permet pas de bien suivre ce que tu fais.

<img width="1305" alt="Screenshot 2024-08-04 at 20 35 42" src="https://github.com/user-attachments/assets/cabb1862-4b66-41ba-866b-1f6186641722">

Lien utile : https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/

**Bravo pour l’effort fourni. En prenant en compte ces retours, je suis convaincu que cela t'aidera à t'améliorer et à devenir encore meilleur.**

**Comment by Romulad** [comment]
Pour les commit, j'ai été assez brouillon, je l'admet 😪

Oui certainement je les prendrai en compte. Merci pour le temps consacré 🙏 @noahdjroton
